- name: Setting up Docker and Kubernetes in all machines
  hosts: all
  roles:
    - role: common

- name: Initializing the cluster from the master node
  hosts: demo-master-*
  gather_facts: false
  roles:
    - role: master-k8s-init

- name: Joining the worker nodes to the cluster
  hosts: demo-worker-*
  gather_facts: false
  roles:
    - role: join-cluster

- name: Joining the storage nodes to the cluster (if present)
  hosts: demo-storage-*
  gather_facts: false
  roles:
    - role: join-cluster
      when: asymmetric_storage | bool

- name: Installing Calico (Networking provider)
  hosts: demo-master-*
  gather_facts: false
  roles:
    - role: master-calico

- name: Labelling and taining storage nodes
  hosts: demo-master-*
  gather_facts: false
  roles:
    - role: master-label-taints
      when: asymmetric_storage | bool
