---
- name: Fetching the join command from host machine
  copy:
    src: "{{ resources_path }}kubeadm/join-command.sh"
    dest: /tmp/
    mode: 0777

- name: Joining the node to cluster
  become: yes
  command: sh /tmp/join-command.sh
