### CALICO

- name: Download Calico
  command: curl https://projectcalico.docs.tigera.io/manifests/calico.yaml -O

- name: Install calico
  command: kubectl apply -f calico.yaml

- name: Waiting for Calico pods init
  command: kubectl rollout status deployment/calico-kube-controllers -n kube-system
  ignore_errors: yes
